import { useCallback, useEffect, useRef, useState } from 'react'; import * as inventoryApi from '../services/inventoryService'; import { getMedicineOptions } from '../services/medicineService'; import { getInventoryErrorMessage } from '../utils/inventoryHelpers';
const paginationDefault={page:1,limit:10,totalRecords:0,totalPages:1,hasNextPage:false,hasPreviousPage:false};
const inventoryDefault={search:'',status:'',categoryId:'',companyId:'',stockStatus:'',expiryStatus:'',sortBy:'medicine_name',sortDirection:'asc',page:1,limit:10};
const historyDefault={search:'',medicineId:'',transactionType:'',dateFrom:'',dateTo:'',sortDirection:'desc',page:1,limit:10}; const medicineHistoryDefault={transactionType:'',dateFrom:'',dateTo:'',page:1,limit:5};
export default function useInventory(){
 const mounted=useRef(true); const inventoryRequest=useRef(0); const historyRequest=useRef(0); const [activeTab,setActiveTab]=useState('inventory'); const [inventory,setInventory]=useState([]); const [summary,setSummary]=useState(null); const [history,setHistory]=useState([]); const [inventoryPagination,setInventoryPagination]=useState(paginationDefault); const [historyPagination,setHistoryPagination]=useState(paginationDefault); const [inventoryFilters,setInventoryFilters]=useState(inventoryDefault); const [historyFilters,setHistoryFilters]=useState(historyDefault); const [debouncedInventorySearch,setDebouncedInventorySearch]=useState(''); const [debouncedHistorySearch,setDebouncedHistorySearch]=useState(''); const [options,setOptions]=useState({categories:[],companies:[]}); const [selectedMedicine,setSelectedMedicine]=useState(null); const [selectedMedicineHistory,setSelectedMedicineHistory]=useState(null); const [medicineHistoryFilters,setMedicineHistoryFilters]=useState(medicineHistoryDefault); const [medicineHistoryPagination,setMedicineHistoryPagination]=useState(paginationDefault); const [modals,setModals]=useState({adjustment:false,history:false}); const [isLoadingInventory,setIsLoadingInventory]=useState(true); const [isLoadingSummary,setIsLoadingSummary]=useState(true); const [isLoadingHistory,setIsLoadingHistory]=useState(false); const [isLoadingMedicineHistory,setIsLoadingMedicineHistory]=useState(false); const [isAdjusting,setIsAdjusting]=useState(false); const [errors,setErrors]=useState({inventory:null,summary:null,history:null,medicineHistory:null}); const [toast,setToast]=useState(null);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]); useEffect(()=>{const t=setTimeout(()=>setDebouncedInventorySearch(inventoryFilters.search.trim()),400);return()=>clearTimeout(t);},[inventoryFilters.search]); useEffect(()=>{const t=setTimeout(()=>setDebouncedHistorySearch(historyFilters.search.trim()),400);return()=>clearTimeout(t);},[historyFilters.search]);
 const fetchInventory=useCallback(async({quiet=false}={})=>{const id=++inventoryRequest.current;if(!quiet)setIsLoadingInventory(true);setErrors(e=>({...e,inventory:null}));try{const r=await inventoryApi.getInventory({...inventoryFilters,search:debouncedInventorySearch||undefined});if(mounted.current&&id===inventoryRequest.current){setInventory(r.data||[]);setInventoryPagination({...paginationDefault,...r.pagination});}}catch(e){if(mounted.current&&id===inventoryRequest.current)setErrors(x=>({...x,inventory:e}));}finally{if(mounted.current&&id===inventoryRequest.current)setIsLoadingInventory(false);}},[debouncedInventorySearch,inventoryFilters.categoryId,inventoryFilters.companyId,inventoryFilters.expiryStatus,inventoryFilters.limit,inventoryFilters.page,inventoryFilters.sortBy,inventoryFilters.sortDirection,inventoryFilters.status,inventoryFilters.stockStatus]);
 const fetchSummary=useCallback(async()=>{setIsLoadingSummary(true);setErrors(e=>({...e,summary:null}));try{const data=await inventoryApi.getInventorySummary();if(mounted.current)setSummary(data);}catch(e){if(mounted.current)setErrors(x=>({...x,summary:e}));}finally{if(mounted.current)setIsLoadingSummary(false);}},[]);
 const fetchHistory=useCallback(async()=>{if(historyFilters.dateFrom&&historyFilters.dateTo&&historyFilters.dateFrom>historyFilters.dateTo)return;const id=++historyRequest.current;setIsLoadingHistory(true);setErrors(e=>({...e,history:null}));try{const r=await inventoryApi.getInventoryHistory({...historyFilters,search:debouncedHistorySearch||undefined});if(mounted.current&&id===historyRequest.current){setHistory(r.data||[]);setHistoryPagination({...paginationDefault,...r.pagination});}}catch(e){if(mounted.current&&id===historyRequest.current)setErrors(x=>({...x,history:e}));}finally{if(mounted.current&&id===historyRequest.current)setIsLoadingHistory(false);}},[debouncedHistorySearch,historyFilters.dateFrom,historyFilters.dateTo,historyFilters.limit,historyFilters.medicineId,historyFilters.page,historyFilters.sortDirection,historyFilters.transactionType]);
 const fetchMedicineHistory=useCallback(async()=>{if(!selectedMedicine||medicineHistoryFilters.dateFrom&&medicineHistoryFilters.dateTo&&medicineHistoryFilters.dateFrom>medicineHistoryFilters.dateTo)return;setIsLoadingMedicineHistory(true);setErrors(e=>({...e,medicineHistory:null}));try{const r=await inventoryApi.getMedicineInventoryHistory(selectedMedicine.medicineId,medicineHistoryFilters);if(mounted.current){setSelectedMedicineHistory(r.data);setMedicineHistoryPagination({...paginationDefault,...r.pagination});}}catch(e){if(mounted.current)setErrors(x=>({...x,medicineHistory:e}));}finally{if(mounted.current)setIsLoadingMedicineHistory(false);}},[medicineHistoryFilters,selectedMedicine]);
 useEffect(()=>{fetchInventory();},[fetchInventory]); useEffect(()=>{fetchSummary();getMedicineOptions().then(data=>{if(mounted.current)setOptions(data||{categories:[],companies:[]});}).catch(()=>{});},[fetchSummary]); useEffect(()=>{if(activeTab==='history')fetchHistory();},[activeTab,fetchHistory]); useEffect(()=>{if(modals.history)fetchMedicineHistory();},[fetchMedicineHistory,modals.history]);
 const changeInventoryFilter=useCallback((field,value)=>setInventoryFilters(f=>field==='sort'?{...f,...value,page:1}:{...f,[field]:value,page:1}),[]); const changeHistoryFilter=useCallback((field,value)=>setHistoryFilters(f=>({...f,[field]:value,page:1})),[]); const changeMedicineHistoryFilter=useCallback((field,value)=>setMedicineHistoryFilters(f=>({...f,[field]:value,page:1})),[]);
 const openAdjustmentModal=useCallback(m=>{setSelectedMedicine(m);setModals({adjustment:true,history:false});},[]); const openMedicineHistoryModal=useCallback(m=>{setSelectedMedicine(m);setSelectedMedicineHistory(null);setMedicineHistoryFilters(medicineHistoryDefault);setModals({adjustment:false,history:true});},[]); const closeModals=useCallback(()=>{if(!isAdjusting){setModals({adjustment:false,history:false});setSelectedMedicine(null);}},[isAdjusting]);
 const adjustStock=useCallback(async payload=>{setIsAdjusting(true);try{const r=await inventoryApi.adjustMedicineStock(selectedMedicine.medicineId,payload);if(mounted.current){setToast({type:'success',message:r.message||'Medicine stock adjusted successfully'});setModals({adjustment:false,history:false});setSelectedMedicine(null);await Promise.all([fetchInventory({quiet:true}),fetchSummary(),activeTab==='history'?fetchHistory():Promise.resolve()]);}return r;}catch(e){if(mounted.current)setToast({type:'error',message:getInventoryErrorMessage(e,'Unable to adjust medicine stock')});throw e;}finally{if(mounted.current)setIsAdjusting(false);}},[activeTab,fetchHistory,fetchInventory,fetchSummary,selectedMedicine]);
 const refreshInventory=useCallback(async()=>{await Promise.all([fetchInventory(),fetchSummary()]);if(mounted.current)setToast({type:'success',message:'Inventory refreshed successfully'});},[fetchInventory,fetchSummary]);
 return {activeTab,setActiveTab,inventory,summary,history,inventoryPagination,historyPagination,inventoryFilters,historyFilters,options,selectedMedicine,selectedMedicineHistory,medicineHistoryFilters,medicineHistoryPagination,modals,isLoadingInventory,isLoadingSummary,isLoadingHistory,isLoadingMedicineHistory,isAdjusting,errors,toast,setToast,fetchInventory,fetchSummary,fetchHistory,fetchMedicineHistory,refreshInventory,refreshHistory:fetchHistory,changeInventoryFilter,changeHistoryFilter,changeMedicineHistoryFilter,clearInventoryFilters:()=>setInventoryFilters(inventoryDefault),clearHistoryFilters:()=>setHistoryFilters(historyDefault),setInventoryPage:p=>setInventoryFilters(f=>({...f,page:p})),setHistoryPage:p=>setHistoryFilters(f=>({...f,page:p})),setMedicineHistoryPage:p=>setMedicineHistoryFilters(f=>({...f,page:p})),openAdjustmentModal,openMedicineHistoryModal,closeModals,adjustStock};
}
