import { useCallback, useEffect, useRef, useState } from 'react';
import * as api from '../services/medicineService';
import { getMedicineErrorMessage } from '../utils/medicineHelpers';

const paginationDefault = { page: 1, limit: 10, totalRecords: 0, totalPages: 1, hasNextPage: false, hasPreviousPage: false };
const filtersDefault = { search: '', status: '', categoryId: '', companyId: '', stockStatus: '', expiryStatus: '', sortBy: 'created_at', sortDirection: 'desc', page: 1, limit: 10 };
const optionsDefault = { categories: [], companies: [], statuses: ['active', 'inactive'] };
const closed = { create: false, edit: false, details: false, delete: false, status: false };

export default function useMedicines() {
  const [medicines, setMedicines] = useState([]); const [pagination, setPagination] = useState(paginationDefault); const [filters, setFilters] = useState(filtersDefault); const [debouncedSearch, setDebouncedSearch] = useState('');
  const [options, setOptions] = useState(optionsDefault); const [isLoading, setIsLoading] = useState(true); const [isRefreshing, setIsRefreshing] = useState(false); const [isLoadingOptions, setIsLoadingOptions] = useState(true);
  const [error, setError] = useState(null); const [selectedMedicine, setSelectedMedicine] = useState(null); const [modals, setModals] = useState(closed); const [mutation, setMutation] = useState(null); const [isDetailsLoading, setIsDetailsLoading] = useState(false); const [toast, setToast] = useState(null);
  const mounted = useRef(true); const requestId = useRef(0);
  useEffect(() => { const timer = setTimeout(() => setDebouncedSearch(filters.search.trim()), 400); return () => clearTimeout(timer); }, [filters.search]);
  const fetchOptions = useCallback(async () => { setIsLoadingOptions(true); try { const data = await api.getMedicineOptions(); if (mounted.current) setOptions({ ...optionsDefault, ...data }); } catch (requestError) { if (mounted.current) setToast({ type: 'error', message: getMedicineErrorMessage(requestError, 'Unable to load medicine form options.') }); } finally { if (mounted.current) setIsLoadingOptions(false); } }, []);
  const fetchMedicines = useCallback(async ({ refreshing = false } = {}) => {
    const id = ++requestId.current; refreshing ? setIsRefreshing(true) : setIsLoading(true); setError(null);
    try { const response = await api.getMedicines({ page: filters.page, limit: filters.limit, sortBy: filters.sortBy, sortDirection: filters.sortDirection, search: debouncedSearch || undefined, status: filters.status || undefined, categoryId: filters.categoryId || undefined, companyId: filters.companyId || undefined, stockStatus: filters.stockStatus || undefined, expiryStatus: filters.expiryStatus || undefined }); if (mounted.current && id === requestId.current) { setMedicines(response.data || []); setPagination({ ...paginationDefault, ...response.pagination }); } }
    catch (requestError) { if (mounted.current && id === requestId.current) { setError(requestError); setToast({ type: 'error', message: 'Unable to load medicines.' }); } }
    finally { if (mounted.current && id === requestId.current) { setIsLoading(false); setIsRefreshing(false); } }
  }, [debouncedSearch, filters.categoryId, filters.companyId, filters.expiryStatus, filters.limit, filters.page, filters.sortBy, filters.sortDirection, filters.status, filters.stockStatus]);
  useEffect(() => { mounted.current = true; fetchOptions(); return () => { mounted.current = false; }; }, [fetchOptions]);
  useEffect(() => { mounted.current = true; fetchMedicines(); return () => { mounted.current = false; }; }, [fetchMedicines]);
  const refreshMedicines = useCallback(async () => { await Promise.all([fetchMedicines({ refreshing: true }), fetchOptions()]); }, [fetchMedicines, fetchOptions]);
  const setFilter = useCallback((field, value) => setFilters((current) => ({ ...current, [field]: value, page: 1 })), []);
  const setSearch = useCallback((v) => setFilter('search', v), [setFilter]); const setStatus = useCallback((v) => setFilter('status', v), [setFilter]); const setCategory = useCallback((v) => setFilter('categoryId', v), [setFilter]); const setCompany = useCallback((v) => setFilter('companyId', v), [setFilter]); const setStockStatus = useCallback((v) => setFilter('stockStatus', v), [setFilter]); const setExpiryStatus = useCallback((v) => setFilter('expiryStatus', v), [setFilter]);
  const setSort = useCallback((value) => { const [sortBy, sortDirection] = value.split(':'); setFilters((current) => ({ ...current, sortBy, sortDirection, page: 1 })); }, []); const setPage = useCallback((page) => setFilters((current) => ({ ...current, page })), []); const clearFilters = useCallback(() => { setFilters(filtersDefault); setDebouncedSearch(''); }, []);
  const closeModals = useCallback(() => { setModals(closed); setSelectedMedicine(null); setIsDetailsLoading(false); }, []); const openCreateModal = useCallback(() => { setSelectedMedicine(null); setModals({ ...closed, create: true }); }, []); const openEditModal = useCallback((m) => { setSelectedMedicine(m); setModals({ ...closed, edit: true }); }, []); const openDeleteModal = useCallback((m) => { setSelectedMedicine(m); setModals({ ...closed, delete: true }); }, []); const openStatusModal = useCallback((m) => { setSelectedMedicine({ ...m, nextStatus: m.status === 'active' ? 'inactive' : 'active' }); setModals({ ...closed, status: true }); }, []);
  const openDetailsModal = useCallback(async (m) => { setSelectedMedicine(m); setModals({ ...closed, details: true }); setIsDetailsLoading(true); try { const details = await api.getMedicineById(m.id); if (mounted.current) setSelectedMedicine(details); } catch (e) { if (mounted.current) setToast({ type: 'error', message: getMedicineErrorMessage(e, 'Unable to load medicine details.') }); } finally { if (mounted.current) setIsDetailsLoading(false); } }, []);
  const mutate = useCallback(async (kind, request, fallback, rethrow = false) => { setMutation(kind); try { const response = await request(); if (mounted.current) { setToast({ type: 'success', message: response.message || fallback }); closeModals(); await fetchMedicines({ refreshing: true }); } return response; } catch (e) { if (mounted.current) setToast({ type: 'error', message: getMedicineErrorMessage(e) }); if (rethrow) throw e; return null; } finally { if (mounted.current) setMutation(null); } }, [closeModals, fetchMedicines]);
  const createMedicine = useCallback((data) => mutate('create', () => api.createMedicine(data), 'Medicine created successfully', true), [mutate]); const updateMedicine = useCallback((data) => mutate('update', () => api.updateMedicine(selectedMedicine.id, data), 'Medicine updated successfully', true), [mutate, selectedMedicine]); const updateStatus = useCallback(() => mutate('status', () => api.updateMedicineStatus(selectedMedicine.id, selectedMedicine.nextStatus), 'Medicine status updated successfully'), [mutate, selectedMedicine]); const deleteMedicine = useCallback(() => mutate('delete', () => api.deleteMedicine(selectedMedicine.id), 'Medicine deleted successfully'), [mutate, selectedMedicine]); const clearToast = useCallback(() => setToast(null), []);
  return { medicines, pagination, filters, options, isLoading, isRefreshing, isLoadingOptions, error, selectedMedicine, modals, mutation, isDetailsLoading, toast, refreshMedicines, setSearch, setStatus, setCategory, setCompany, setStockStatus, setExpiryStatus, setSort, clearFilters, setPage, openCreateModal, openEditModal, openDetailsModal, openDeleteModal, openStatusModal, closeModals, createMedicine, updateMedicine, updateStatus, deleteMedicine, clearToast };
}
