const ApiError=require('../utils/ApiError');const Medicine=require('../models/Medicine');const InventoryLog=require('../models/InventoryLog');const {withTransaction}=require('./databaseService');const medicineService=require('./medicineService');const {getStockStatus}=require('../utils/medicineMapper');
async function getInventory(q){try{return await Medicine.getInventoryList(q)}catch(e){throw new ApiError(500,'Unable to retrieve inventory','INTERNAL_SERVER_ERROR')}}
async function getInventorySummary(){try{return {...await Medicine.getInventorySummary(),generatedAt:new Date().toISOString()}}catch(e){throw new ApiError(500,'Unable to retrieve inventory summary','INTERNAL_SERVER_ERROR')}}
function checkDates(q){if(q.dateFrom&&q.dateTo&&q.dateFrom>q.dateTo)throw new ApiError(422,'Date from cannot be after date to','INVALID_DATE_RANGE')}
async function getInventoryHistory(q){checkDates(q);try{return await InventoryLog.findAllWithRelations(q)}catch(e){throw new ApiError(500,'Unable to retrieve inventory history','INVENTORY_HISTORY_FAILED')}}
async function getMedicineInventoryHistory(id,q){checkDates(q);const medicine=await medicineService.getMedicineById(id);try{const result=await InventoryLog.findByMedicineId(id,q);return {medicine:{id:medicine.id,medicineName:medicine.medicineName,stockQuantity:medicine.stockQuantity,minimumStock:medicine.minimumStock,stockStatus:medicine.stockStatus},history:result.data,pagination:result.pagination}}catch(e){throw new ApiError(500,'Unable to retrieve medicine inventory history','INVENTORY_HISTORY_FAILED')}}
async function adjustMedicineStock(id,adminId,data){
  try{return await withTransaction(async(connection)=>{const medicine=await Medicine.findByIdForUpdate(id,connection);if(!medicine)throw new ApiError(404,'Medicine not found','MEDICINE_NOT_FOUND');const previous=Number(medicine.stock_quantity);const qty=Number(data.quantity);let change;if(data.transactionType==='stockIn')change=qty;else if(data.transactionType==='stockOut')change=-qty;else if(data.transactionType==='correction')change=qty-previous;else throw new ApiError(422,'Invalid transaction type','INVALID_TRANSACTION_TYPE');const next=previous+change;if(next<0)throw new ApiError(409,'Insufficient stock for this adjustment','INSUFFICIENT_STOCK');await Medicine.updateStockQuantity(id,next,connection);const created=await InventoryLog.createLog({medicineId:id,adminId,transactionType:data.transactionType,quantity:qty,quantityChange:change,previousQuantity:previous,newQuantity:next,reason:data.reason.trim(),notes:data.notes?.trim()||null},connection);return {medicine:{id:medicine.id,medicineName:medicine.medicine_name,previousQuantity:previous,quantityChange:change,stockQuantity:next,minimumStock:Number(medicine.minimum_stock),stockStatus:getStockStatus(next,Number(medicine.minimum_stock))},logId:created.id};});}catch(e){if(['MEDICINE_NOT_FOUND','INVALID_TRANSACTION_TYPE','INSUFFICIENT_STOCK'].includes(e.errorCode))throw e;throw new ApiError(500,'Unable to adjust medicine stock','INVENTORY_ADJUSTMENT_FAILED')}
}
async function getAdjustmentResult(result){const inventoryLog=await InventoryLog.findByIdWithRelations(result.logId);return {medicine:result.medicine,inventoryLog}}
module.exports={getInventory,getInventorySummary,getInventoryHistory,getMedicineInventoryHistory,adjustMedicineStock:async(...args)=>getAdjustmentResult(await adjustMedicineStock(...args))};
