const ApiError = require('../utils/ApiError'); const Supplier = require('../models/Supplier'); const { mapSupplierInput } = require('../utils/supplierMapper');
async function getSuppliers(query) { try { return await Supplier.findAllWithSummary(query); } catch (error) { throw new ApiError(500, 'Unable to retrieve suppliers', 'INTERNAL_SERVER_ERROR'); } }
async function getSupplierOptions() { try { return await Supplier.findActiveOptions(); } catch (error) { throw new ApiError(500, 'Unable to retrieve supplier options', 'INTERNAL_SERVER_ERROR'); } }
async function getSupplierById(id) { let supplier; try { supplier = await Supplier.findByIdWithSummary(id); } catch (error) { throw new ApiError(500, 'Unable to retrieve supplier', 'INTERNAL_SERVER_ERROR'); } if (!supplier) throw new ApiError(404, 'Supplier not found', 'SUPPLIER_NOT_FOUND'); return supplier; }
async function assertUnique(data, excludeId = null) { if (await Supplier.existsByNameInsensitive(data.supplier_name, excludeId)) throw new ApiError(409, 'A supplier with this name already exists', 'SUPPLIER_ALREADY_EXISTS'); if (data.email && await Supplier.findByEmail(data.email, excludeId)) throw new ApiError(409, 'A supplier with this email already exists', 'SUPPLIER_EMAIL_EXISTS'); }
async function createSupplier(input) { const data = mapSupplierInput(input); try { await assertUnique(data); return await Supplier.createSupplier(data); } catch (error) { if (['SUPPLIER_ALREADY_EXISTS', 'SUPPLIER_EMAIL_EXISTS'].includes(error.errorCode)) throw error; throw new ApiError(500, 'Unable to create supplier', 'SUPPLIER_CREATE_FAILED'); } }
async function updateSupplier(id, input) { const data = mapSupplierInput(input); try { await getSupplierById(id); await assertUnique(data, id); return await Supplier.updateSupplier(id, data); } catch (error) { if (['SUPPLIER_NOT_FOUND', 'SUPPLIER_ALREADY_EXISTS', 'SUPPLIER_EMAIL_EXISTS'].includes(error.errorCode)) throw error; throw new ApiError(500, 'Unable to update supplier', 'SUPPLIER_UPDATE_FAILED'); } }
async function updateSupplierStatus(id, status) { try { await getSupplierById(id); return await Supplier.updateStatus(id, status); } catch (error) { if (error.errorCode === 'SUPPLIER_NOT_FOUND') throw error; throw new ApiError(500, 'Unable to update supplier status', 'SUPPLIER_UPDATE_FAILED'); } }
async function deleteSupplier(id) { try { await getSupplierById(id); if (await Supplier.getPurchaseCount(id) > 0) throw new ApiError(409, 'This supplier cannot be deleted because purchase records are linked to it', 'SUPPLIER_IN_USE'); await Supplier.deleteSupplier(id); } catch (error) { if (['SUPPLIER_NOT_FOUND', 'SUPPLIER_IN_USE'].includes(error.errorCode)) throw error; throw new ApiError(500, 'Unable to delete supplier', 'SUPPLIER_DELETE_FAILED'); } }
module.exports = { getSuppliers, getSupplierOptions, getSupplierById, createSupplier, updateSupplier, updateSupplierStatus, deleteSupplier };
